export const APP_LANGUAGES = ["en", "gu", "hi"] as const;

export type AppLanguage = (typeof APP_LANGUAGES)[number];

export const DEFAULT_APP_LANGUAGE: AppLanguage = "en";

export const appResources = {
    en: {
        common: {
            appName: "Ganatri POS",
            loading: "Loading",
            retry: "Retry",
            cancel: "Cancel",
            save: "Save",
            logout: "Logout",
            loggingOut: "Logging out...",
            loggedOutTitle: "Logged out",
            loggedOutMessage: "You have been logged out successfully.",
            logoutFailedTitle: "Logout failed",
            genericError: "Please try again.",
            language: "Language",
            english: "English",
            gujarati: "ગુજરાતી",
            hindi: "हिन्दी",
        },
        pos: {
            workspaceTitle: "POS workspace",
            foundationMessage:
                "The POS foundation is ready. Product selection, Cart, and checkout will be added in their planned phases.",
            unlockTitle: "Unlock POS",
            unlockSubtitle: "Use your Store Device credentials to start billing.",
            organizationUsername: "Organization username",
            deviceUsername: "Device username",
            deviceSecret: "Device secret",
            unlockPos: "Unlock POS",
            unlockingPos: "Unlocking POS...",
            invalidField: "Please check this field.",
            invalidCredentials: "The Device credentials are not valid.",
            inactiveDevice: "This Device is inactive. Contact your administrator.",
            networkFailure: "Could not reach the POS service. Check the connection and try again.",
            unlockFailed: "POS could not be unlocked. Please try again.",
            storageUnavailable: "Secure POS storage is unavailable. Please try again.",
            sessionVerificationFailed: "The POS session could not be verified. Please unlock again.",
            newSale: "New Sale",
            bills: "Bills",
            billsSales: "Sales",
            billsDrafts: "Drafts",
            draft: "Draft",
            saleStatusVoided: "Voided",
            customers: "Customers",
            reports: "Reports",
            settings: "Settings",
            tables: "Tables",
            kitchen: "Kitchen",
            kitchenSubtitle: "Complete pending kitchen tickets.",
            kitchenUnavailable: "Kitchen tickets are not enabled for this Store.",
            kitchenLoading: "Loading Kitchen...",
            kitchenLoadFailed: "Kitchen tickets could not be loaded.",
            kitchenEmpty: "No pending kitchen tickets.",
            kotNumber: "KOT {{number}}",
            kotTable: "Table: {{table}}",
            kotItems: "Items",
            completeKot: "Complete KOT",
            kotCompleteFailed: "KOT could not be completed. Please try again.",
            sendToKitchen: "Send to kitchen",
            kotSent: "KOT sent to kitchen.",
            kotSendFailed: "KOT could not be sent. Your Cart is ready to retry.",
            tablesSubtitle: "Start or reopen a restaurant Table Order.",
            tablesUnavailable: "Table management is not enabled for this Store.",
            tablesLoading: "Loading Tables...",
            tablesLoadFailed: "Tables could not be loaded.",
            tablesEmpty: "No Tables are configured.",
            tableCapacity: "Seats: {{count}}",
            tableTotal: "Current total: {{total}}",
            startTableOrder: "Start order",
            openTableOrder: "Open order",
            tableStateFree: "Free",
            tableStateAllocated: "Allocated",
            tableStateEngaged: "Engaged",
            tableStateReadyToBill: "Ready to bill",
            tableStatePaymentDue: "Payment due",
            tableStatePaid: "Paid",
            comingSoon: "This workspace will be added in its planned phase.",
            back: "Back",
            billsSubtitle: "Find today's Sales and check their settlement status.",
            billsSearch: "Search Bills",
            billsSearchPlaceholder: "Search Sale number or Customer",
            billsFilter: "Show filters",
            billsHideFilters: "Hide filters",
            billsDate: "Date",
            billsToday: "Today",
            billsAllDates: "All dates",
            billsPaymentStatus: "Payment status",
            billsPaymentMethod: "Payment method",
            billsAll: "All",
            billsClearFilters: "Clear filters",
            billsLoading: "Loading Bills...",
            billsLoadFailed: "Bills could not be loaded.",
            billsNoSales: "No Sales found for this date.",
            billsNoDrafts: "No Drafts found.",
            billsNoMatchingSales: "No Sales match these filters.",
            billsSaleNumber: "Sale number",
            billsCustomer: "Customer",
            billsLoadMore: "Load more Sales",
            saleDetails: "Sale Details",
            saleDetailsComingSoon: "Detailed Sale review will be available in the next Bills step.",
            saleDetailsLoading: "Loading Sale Details...",
            saleDetailsLoadFailed: "Sale Details could not be loaded.",
            saleDetailsNoData: "Sale Details are unavailable.",
            saleItems: "Items",
            salePayments: "Payments",
            saleSubtotal: "Subtotal",
            saleDiscount: "Discount",
            saleTotal: "Total",
            resumeDraft: "Resume Draft",
            resumeDraftConfirm: "Replace the current Cart with this Draft?",
            draftResumeFailed: "This Draft cannot be resumed because its Catalog data is no longer available.",
            discardDraftConfirm: "Discard this Draft? This action cannot be undone.",
            restaurantTools: "Restaurant tools",
            productSearch: "Product search",
            searchProductsPlaceholder: "Search products",
            catalogLoading: "Loading Products and Categories...",
            catalogLoadFailed: "Products and Categories could not be loaded.",
            catalogAccessDenied: "This Store does not have access to the POS catalog.",
            catalogEmpty: "No Products or Categories are available yet.",
            catalogReady: "Catalog loaded. Product selection will be added next.",
            allCategories: "All",
            noProductsFound: "No Products found for this search.",
            configurationComingSoon: "Configuration will be available soon.",
            scanBarcode: "Scan barcode",
            closeScanner: "Close scanner",
            scannerPermissionDenied: "Camera permission is needed to scan. You can still search manually.",
            scannerCameraError: "The camera could not start. You can still search manually.",
            scannerUnknownCode: "No Product matches this code. Search manually or try another code.",
            scannerAmbiguousCode: "More than one Product matches this code. Search manually.",
            scannerAdded: "Product added to Cart.",
            scannerConfigurationComingSoon: "This Product needs configuration before it can be added.",
            allProducts: "All Products",
            recentProducts: "Recent",
            pinnedProducts: "Pinned",
            pinProduct: "Pin Product",
            unpinProduct: "Unpin Product",
            configureProduct: "Configure Product",
            configurationRequired: "Choose the available options before adding this Product.",
            configurationLoading: "Loading Product options...",
            configurationLoadFailed: "Product options could not be loaded.",
            noConfigurationOptions: "No configuration options are available.",
            cancelConfiguration: "Cancel",
            addConfiguredProduct: "Add to Cart",
            cartWithCount: "Cart ({{count}})",
            newSaleSubtitle: "Search, scan, or choose a Product to add it to Cart.",
            serviceMode: "Service mode",
            serviceModeDineIn: "Dine-In",
            serviceModePickUp: "Pick-Up",
            tableOrder: "Table order",
            catalogComingSoon: "Product results will be available in the Catalog phase.",
            cart: "Cart",
            emptyCart: "Cart is empty",
            cartLineUnitPrice: "Unit price: {{price}}",
            cartLineSellingQuantity: "Selling portion: {{quantity}}",
            editSellingQuantity: "Change portion",
            sellingQuantity: "Selling quantity",
            sellingQuantityPlaceholder: "Enter quantity",
            sellingQuantityInvalid: "Enter a positive quantity with up to 2 decimals.",
            applySellingQuantity: "Apply portion",
            cancelSellingQuantity: "Cancel",
            decreaseQuantity: "Decrease quantity",
            increaseQuantity: "Increase quantity",
            removeCartItem: "Remove",
            cartSubtotal: "Subtotal",
            catalogDiscount: "Product discount",
            cartDisplayTotal: "Display total",
            cartDisplayTotalNote: "Final total is confirmed by the server before completion.",
            configurationDetails: "Configuration",
            continueToPayment: "Continue to Payment",
            paymentTitle: "Payment",
            paymentTotal: "Total",
            paymentCollected: "Collected",
            paymentRemaining: "Remaining",
            paymentServerNote: "Final Payment status and totals are confirmed by the server.",
            paymentRow: "Payment {{count}}",
            paymentMethod: "Payment method",
            paymentCash: "Cash",
            paymentUpi: "UPI",
            paymentCard: "Card",
            paymentAmount: "Amount",
            paymentAmountPlaceholder: "Enter amount",
            paymentInvalidAmount: "Enter valid non-negative amounts.",
            paymentOverTotal: "Collected amount cannot exceed the total.",
            addPayment: "Add payment",
            removePayment: "Remove",
            continueToCompleteSale: "Continue to Complete Sale",
            paymentCheckoutComingSoon: "Sale completion will be available in the next step.",
            backToCart: "Back to Cart",
            paymentStatusPaid: "Paid",
            paymentStatusPaidDescription: "The Sale is fully settled.",
            paymentStatusPartial: "Partial",
            paymentStatusPartialDescription: "Some payment was collected; the remaining amount is due.",
            paymentStatusDue: "Due",
            paymentStatusDueDescription: "No payment is recorded yet; the remaining amount is due.",
            completeSale: "Complete Sale",
            saleCompleteTitle: "Sale Complete",
            saleCompleteMessage: "The Sale was recorded successfully.",
            saleNumber: "Sale number",
            saleCustomer: "Customer",
            saleResultMissing: "The completed Sale is not available. Start a new Sale.",
            checkoutFailed: "Sale could not be completed. Your Cart is ready to retry.",
            showReceipt: "Show Receipt",
            hideReceipt: "Hide Receipt",
            shareReceipt: "Share Receipt",
            receiptShared: "Receipt shared.",
            receiptShareDismissed: "Sharing was cancelled. The Sale is still complete.",
            receiptShareFailed: "Receipt could not be shared. Try again.",
            walkInCustomer: "Walk-in customer",
            selectCustomer: "Select Customer",
            changeCustomer: "Change Customer",
            clearCustomer: "Use Walk-in",
            customerPickerTitle: "Choose a Customer",
            customerSearch: "Customer search",
            customersDirectorySubtitle: "Find Customers and review their Sales history.",
            addCustomer: "Add Customer",
            showCustomerFilters: "Show filters",
            hideCustomerFilters: "Hide filters",
            customerStatus: "Customer status",
            customerSort: "Sort",
            customerActive: "Active",
            customerInactive: "Inactive",
            customerDue: "Due",
            customerAll: "All",
            customerSortNameAsc: "Name A–Z",
            customerSortNameDesc: "Name Z–A",
            customerSortNewest: "Newest",
            customerSaveFailed: "Customer could not be saved.",
            customersDirectoryEmpty: "No Customers found.",
            customerNoPhone: "No phone",
            customerBalance: "Balance",
            viewCustomer: "View",
            customersLoadMore: "Load more Customers",
            editCustomer: "Edit Customer",
            useCustomerForSale: "Use for current Sale",
            customerSalesHistory: "Sales history",
            salesHistoryLoading: "Loading Sales history...",
            salesHistoryFailed: "Sales history could not be loaded.",
            salesHistoryEmpty: "No Sales history found.",
            searchCustomersPlaceholder: "Search by name or phone",
            customersLoading: "Loading Customers...",
            customersLoadFailed: "Customers could not be loaded.",
            noCustomersFound: "No Customers found.",
            createCustomer: "Create Customer",
            quickCustomer: "Quick Customer",
            customerName: "Customer name",
            customerNamePlaceholder: "Enter name",
            customerPhone: "Customer phone",
            customerPhonePlaceholder: "Optional phone",
            customerNameRequired: "Customer name is required.",
            customerPhoneInvalid: "Enter a valid phone number.",
            customerCreateFailed: "Customer could not be created. Please try again.",
            cancelCustomerCreation: "Cancel",
            saveCustomer: "Save Customer",
            orderDiscount: "Order discount",
            addDiscount: "Add discount",
            editDiscount: "Edit discount",
            removeDiscount: "Remove discount",
            discountEditorTitle: "Discount",
            discountModeAmount: "Amount",
            discountModePercent: "Percent",
            discountValue: "Discount value",
            discountPercentPlaceholder: "Enter percentage",
            discountAmountPlaceholder: "Enter amount",
            discountInvalid: "Enter a valid discount within the current total.",
            cancelDiscount: "Cancel",
            applyDiscount: "Apply discount",
            saveDraft: "Save draft",
            updateDraft: "Update draft",
            discardDraft: "Discard draft",
            draftSaved: "Draft saved.",
            draftDiscarded: "Draft discarded.",
            draftActionFailed: "Draft action failed. Please try again.",
            reportsSubtitle: "Review completed Sales and Products Sold.",
            reportsDate: "Date",
            reportsToday: "Today",
            reportsAllDates: "All dates",
            reportsLoading: "Loading Reports...",
            reportsLoadFailed: "Reports could not be loaded.",
            reportsEmpty: "No report data found.",
            salesSummary: "Sales summary",
            salesCount: "Sales count",
            salesValue: "Sales value",
            collectedAmount: "Collected amount",
            dueAmount: "Due amount",
            averageSaleValue: "Average Sale value",
            productsSold: "Products Sold",
            noProductsSold: "No Products Sold found.",
            settingsSubtitle: "Adjust language, appearance, printer access, and session settings.",
            settingsTheme: "Theme",
            themeLight: "Light",
            themeDark: "Dark",
            themeSystem: "System",
            themeActive: "Active theme: {{theme}}",
            settingsDisplaySize: "Display size",
            displayStandard: "Standard",
            displayLarge: "Large",
            settingsPrinter: "Printer",
            printerSettings: "Printer settings",
            printerSettingsDeferred: "Bluetooth printer setup will be available in the printing phase.",
            storeInformation: "Store and Device information",
            organizationName: "Organization",
            storeName: "Store",
            deviceName: "Device",
            printerSettingsSubtitle: "Discover and test a Bluetooth thermal printer.",
            selectedPrinter: "Selected printer",
            discoverPrinters: "Discover printers",
            connectPrinter: "Connect printer",
            disconnectPrinter: "Disconnect printer",
            testPrint: "Test print",
            retryPrinter: "Retry printer action",
            printerDisconnected: "Printer disconnected",
            printerDiscovering: "Discovering printers...",
            printerConnecting: "Connecting printer...",
            printerConnected: "Printer connected",
            printerTesting: "Testing printer...",
            printerPrinting: "Printing...",
            printerFailed: "Printer action failed",
            printReceipt: "Print receipt",
            printerPrintFailed: "Receipt could not be printed. The Sale is still complete.",
        },
    },
    gu: {
        common: {
            appName: "ગણત્રી POS",
            loading: "લોડ થઈ રહ્યું છે",
            retry: "ફરી પ્રયાસ કરો",
            cancel: "રદ કરો",
            save: "સાચવો",
            logout: "લૉગઆઉટ",
            loggingOut: "લૉગઆઉટ થઈ રહ્યું છે...",
            loggedOutTitle: "લૉગઆઉટ થયું",
            loggedOutMessage: "તમે સફળતાપૂર્વક લૉગઆઉટ થયા છો.",
            logoutFailedTitle: "લૉગઆઉટ નિષ્ફળ",
            genericError: "કૃપા કરીને ફરી પ્રયાસ કરો.",
            language: "ભાષા",
            english: "English",
            gujarati: "ગુજરાતી",
            hindi: "हिन्दी",
        },
        pos: {
            workspaceTitle: "POS કાર્યસ્થળ",
            foundationMessage:
                "POS પાયો તૈયાર છે. પ્રોડક્ટ પસંદગી, કાર્ટ અને ચેકઆઉટ તેમના નિર્ધારિત તબક્કામાં ઉમેરવામાં આવશે.",
            unlockTitle: "POS અનલૉક કરો",
            unlockSubtitle: "બિલિંગ શરૂ કરવા માટે તમારા સ્ટોર ડિવાઇસની વિગતોનો ઉપયોગ કરો.",
            organizationUsername: "સંસ્થાનું યુઝરનેમ",
            deviceUsername: "ડિવાઇસ યુઝરનેમ",
            deviceSecret: "ડિવાઇસ સિક્રેટ",
            unlockPos: "POS અનલૉક કરો",
            unlockingPos: "POS અનલૉક થઈ રહ્યું છે...",
            invalidField: "કૃપા કરીને આ ફીલ્ડ તપાસો.",
            invalidCredentials: "ડિવાઇસની વિગતો માન્ય નથી.",
            inactiveDevice: "આ ડિવાઇસ નિષ્ક્રિય છે. તમારા એડમિનિસ્ટ્રેટરનો સંપર્ક કરો.",
            networkFailure: "POS સેવા સુધી પહોંચી શકાયું નથી. કનેક્શન તપાસી ફરી પ્રયાસ કરો.",
            unlockFailed: "POS અનલૉક થઈ શક્યું નથી. કૃપા કરીને ફરી પ્રયાસ કરો.",
            storageUnavailable: "સુરક્ષિત POS સ્ટોરેજ ઉપલબ્ધ નથી. કૃપા કરીને ફરી પ્રયાસ કરો.",
            sessionVerificationFailed: "POS સત્રની ચકાસણી થઈ શકી નથી. કૃપા કરીને ફરી અનલૉક કરો.",
            newSale: "નવું વેચાણ",
            bills: "બિલ્સ",
            billsSales: "વેચાણ",
            billsDrafts: "ડ્રાફ્ટ્સ",
            draft: "ડ્રાફ્ટ",
            saleStatusVoided: "રદ કરેલ",
            customers: "ગ્રાહકો",
            reports: "રિપોર્ટ્સ",
            settings: "સેટિંગ્સ",
            tables: "ટેબલ્સ",
            kitchen: "કિચન",
            kitchenSubtitle: "બાકી રહેલા કિચન ટિકિટ્સ પૂર્ણ કરો.",
            kitchenUnavailable: "આ સ્ટોર માટે કિચન ટિકિટ્સ સક્રિય નથી.",
            kitchenLoading: "કિચન લોડ થઈ રહ્યું છે...",
            kitchenLoadFailed: "કિચન ટિકિટ્સ લોડ થઈ શક્યા નથી.",
            kitchenEmpty: "કોઈ બાકી કિચન ટિકિટ નથી.",
            kotNumber: "KOT {{number}}",
            kotTable: "ટેબલ: {{table}}",
            kotItems: "આઇટમ્સ",
            completeKot: "KOT પૂર્ણ કરો",
            kotCompleteFailed: "KOT પૂર્ણ થઈ શક્યો નથી. ફરી પ્રયાસ કરો.",
            sendToKitchen: "કિચનમાં મોકલો",
            kotSent: "KOT કિચનમાં મોકલાયો.",
            kotSendFailed: "KOT મોકલી શકાયો નથી. તમારું કાર્ટ ફરી પ્રયાસ માટે તૈયાર છે.",
            tablesSubtitle: "રેસ્ટોરન્ટ ટેબલ ઓર્ડર શરૂ કરો અથવા ફરી ખોલો.",
            tablesUnavailable: "આ સ્ટોર માટે ટેબલ મેનેજમેન્ટ સક્રિય નથી.",
            tablesLoading: "ટેબલ્સ લોડ થઈ રહ્યા છે...",
            tablesLoadFailed: "ટેબલ્સ લોડ થઈ શક્યા નથી.",
            tablesEmpty: "કોઈ ટેબલ ગોઠવાયેલ નથી.",
            tableCapacity: "બેઠકો: {{count}}",
            tableTotal: "વર્તમાન કુલ: {{total}}",
            startTableOrder: "ઓર્ડર શરૂ કરો",
            openTableOrder: "ઓર્ડર ખોલો",
            tableStateFree: "ખાલી",
            tableStateAllocated: "ફાળવેલ",
            tableStateEngaged: "ચાલુ",
            tableStateReadyToBill: "બિલ માટે તૈયાર",
            tableStatePaymentDue: "ચુકવણી બાકી",
            tableStatePaid: "ચૂકવાયેલ",
            comingSoon: "આ કાર્યસ્થળ તેના નિર્ધારિત તબક્કામાં ઉમેરવામાં આવશે.",
            back: "પાછા",
            billsSubtitle: "આજના વેચાણ શોધો અને તેમની ચુકવણી સ્થિતિ જુઓ.",
            billsSearch: "બિલ શોધો",
            billsSearchPlaceholder: "વેચાણ નંબર અથવા ગ્રાહકથી શોધો",
            billsFilter: "ફિલ્ટર બતાવો",
            billsHideFilters: "ફિલ્ટર છુપાવો",
            billsDate: "તારીખ",
            billsToday: "આજે",
            billsAllDates: "બધી તારીખો",
            billsPaymentStatus: "ચુકવણી સ્થિતિ",
            billsPaymentMethod: "ચુકવણી પદ્ધતિ",
            billsAll: "બધા",
            billsClearFilters: "ફિલ્ટર સાફ કરો",
            billsLoading: "બિલ લોડ થઈ રહ્યા છે...",
            billsLoadFailed: "બિલ લોડ થઈ શક્યા નથી.",
            billsNoSales: "આ તારીખ માટે કોઈ વેચાણ મળ્યાં નથી.",
            billsNoDrafts: "કોઈ ડ્રાફ્ટ મળ્યા નથી.",
            billsNoMatchingSales: "આ ફિલ્ટર સાથે કોઈ વેચાણ મળ્યું નથી.",
            billsSaleNumber: "વેચાણ નંબર",
            billsCustomer: "ગ્રાહક",
            billsLoadMore: "વધુ વેચાણ લોડ કરો",
            saleDetails: "વેચાણની વિગતો",
            saleDetailsComingSoon: "બિલ્સના આગલા તબક્કામાં વેચાણની વિગતવાર સમીક્ષા ઉપલબ્ધ થશે.",
            saleDetailsLoading: "વેચાણની વિગતો લોડ થઈ રહી છે...",
            saleDetailsLoadFailed: "વેચાણની વિગતો લોડ થઈ શકી નથી.",
            saleDetailsNoData: "વેચાણની વિગતો ઉપલબ્ધ નથી.",
            saleItems: "વસ્તુઓ",
            salePayments: "ચુકવણીઓ",
            saleSubtotal: "પેટા સરવાળો",
            saleDiscount: "ડિસ્કાઉન્ટ",
            saleTotal: "કુલ",
            resumeDraft: "ડ્રાફ્ટ ફરી શરૂ કરો",
            resumeDraftConfirm: "હાલના કાર્ટને આ ડ્રાફ્ટથી બદલવો છે?",
            draftResumeFailed: "આ ડ્રાફ્ટ ફરી શરૂ થઈ શકતો નથી કારણ કે તેનો કેટલોગ ડેટા હવે ઉપલબ્ધ નથી.",
            discardDraftConfirm: "આ ડ્રાફ્ટ કાઢી નાખવો છે? આ ક્રિયા પાછી ફેરવી શકાશે નહીં.",
            restaurantTools: "રેસ્ટોરન્ટ સાધનો",
            productSearch: "પ્રોડક્ટ શોધો",
            searchProductsPlaceholder: "પ્રોડક્ટ શોધો",
            catalogLoading: "પ્રોડક્ટ્સ અને કેટેગરીઝ લોડ થઈ રહ્યાં છે...",
            catalogLoadFailed: "પ્રોડક્ટ્સ અને કેટેગરીઝ લોડ થઈ શક્યાં નથી.",
            catalogAccessDenied: "આ સ્ટોરને POS કેટલોગની ઍક્સેસ નથી.",
            catalogEmpty: "હજુ સુધી કોઈ પ્રોડક્ટ અથવા કેટેગરી ઉપલબ્ધ નથી.",
            catalogReady: "કેટલોગ લોડ થયો. પ્રોડક્ટ પસંદગી હવે પછી ઉમેરાશે.",
            allCategories: "બધા",
            noProductsFound: "આ શોધ માટે કોઈ પ્રોડક્ટ મળી નથી.",
            configurationComingSoon: "કન્ફિગરેશન ટૂંક સમયમાં ઉપલબ્ધ થશે.",
            scanBarcode: "બારકોડ સ્કેન કરો",
            closeScanner: "સ્કેનર બંધ કરો",
            scannerPermissionDenied: "સ્કેન કરવા માટે કેમેરાની પરવાનગી જરૂરી છે. તમે હજી પણ જાતે શોધી શકો છો.",
            scannerCameraError: "કેમેરા શરૂ થઈ શક્યો નથી. તમે હજી પણ જાતે શોધી શકો છો.",
            scannerUnknownCode: "આ કોડ સાથે કોઈ પ્રોડક્ટ મળ્યું નથી. જાતે શોધો અથવા બીજો કોડ અજમાવો.",
            scannerAmbiguousCode: "આ કોડ સાથે એકથી વધુ પ્રોડક્ટ મળ્યાં છે. જાતે શોધો.",
            scannerAdded: "પ્રોડક્ટ કાર્ટમાં ઉમેરાયું.",
            scannerConfigurationComingSoon: "કાર્ટમાં ઉમેરતા પહેલાં આ પ્રોડક્ટનું કન્ફિગરેશન જરૂરી છે.",
            allProducts: "બધા પ્રોડક્ટ્સ",
            recentProducts: "તાજેતરના",
            pinnedProducts: "પિન કરેલા",
            pinProduct: "પ્રોડક્ટ પિન કરો",
            unpinProduct: "પ્રોડક્ટ અનપિન કરો",
            configureProduct: "પ્રોડક્ટ કન્ફિગર કરો",
            configurationRequired: "આ પ્રોડક્ટ ઉમેરતા પહેલાં ઉપલબ્ધ વિકલ્પો પસંદ કરો.",
            configurationLoading: "પ્રોડક્ટના વિકલ્પો લોડ થઈ રહ્યા છે...",
            configurationLoadFailed: "પ્રોડક્ટના વિકલ્પો લોડ થઈ શક્યા નથી.",
            noConfigurationOptions: "કોઈ કન્ફિગરેશન વિકલ્પ ઉપલબ્ધ નથી.",
            cancelConfiguration: "રદ કરો",
            addConfiguredProduct: "કાર્ટમાં ઉમેરો",
            cartWithCount: "કાર્ટ ({{count}})",
            newSaleSubtitle: "કાર્ટમાં ઉમેરવા માટે પ્રોડક્ટ શોધો, સ્કેન કરો અથવા પસંદ કરો.",
            serviceMode: "સેવા મોડ",
            serviceModeDineIn: "ડાઇન-ઇન",
            serviceModePickUp: "પિક-અપ",
            tableOrder: "ટેબલ ઓર્ડર",
            catalogComingSoon: "કેટલોગ તબક્કામાં પ્રોડક્ટના પરિણામો ઉપલબ્ધ થશે.",
            cart: "કાર્ટ",
            emptyCart: "કાર્ટ ખાલી છે",
            cartLineUnitPrice: "એકમ કિંમત: {{price}}",
            cartLineSellingQuantity: "વેચાણનો જથ્થો: {{quantity}}",
            editSellingQuantity: "જથ્થો બદલો",
            sellingQuantity: "વેચાણનો જથ્થો",
            sellingQuantityPlaceholder: "જથ્થો દાખલ કરો",
            sellingQuantityInvalid: "2 દશાંશ સુધીનો હકારાત્મક જથ્થો દાખલ કરો.",
            applySellingQuantity: "જથ્થો લાગુ કરો",
            cancelSellingQuantity: "રદ કરો",
            decreaseQuantity: "જથ્થો ઘટાડો",
            increaseQuantity: "જથ્થો વધારો",
            removeCartItem: "દૂર કરો",
            cartSubtotal: "પેટા સરવાળો",
            catalogDiscount: "પ્રોડક્ટ ડિસ્કાઉન્ટ",
            cartDisplayTotal: "ડિસ્પ્લે કુલ",
            cartDisplayTotalNote: "પૂર્ણ કરતા પહેલાં અંતિમ કુલ સર્વર દ્વારા નક્કી થશે.",
            configurationDetails: "કન્ફિગરેશન",
            continueToPayment: "ચુકવણી પર જાઓ",
            paymentTitle: "ચુકવણી",
            paymentTotal: "કુલ",
            paymentCollected: "મળેલી રકમ",
            paymentRemaining: "બાકી",
            paymentServerNote: "અંતિમ ચુકવણી સ્થિતિ અને કુલ સર્વર દ્વારા નક્કી થાય છે.",
            paymentRow: "ચુકવણી {{count}}",
            paymentMethod: "ચુકવણી પદ્ધતિ",
            paymentCash: "રોકડ",
            paymentUpi: "UPI",
            paymentCard: "કાર્ડ",
            paymentAmount: "રકમ",
            paymentAmountPlaceholder: "રકમ દાખલ કરો",
            paymentInvalidAmount: "માન્ય બિન-નકારાત્મક રકમ દાખલ કરો.",
            paymentOverTotal: "મળેલી રકમ કુલ કરતાં વધુ ન હોઈ શકે.",
            addPayment: "ચુકવણી ઉમેરો",
            removePayment: "દૂર કરો",
            continueToCompleteSale: "વેચાણ પૂર્ણ કરવા આગળ વધો",
            paymentCheckoutComingSoon: "વેચાણ પૂર્ણ કરવાનું આગલા પગલામાં ઉપલબ્ધ થશે.",
            backToCart: "કાર્ટ પર પાછા જાઓ",
            paymentStatusPaid: "ચૂકવેલ",
            paymentStatusPaidDescription: "વેચાણની સંપૂર્ણ રકમ ચૂકવાઈ ગઈ છે.",
            paymentStatusPartial: "આંશિક",
            paymentStatusPartialDescription: "થોડી ચુકવણી મળી છે; બાકીની રકમ બાકી છે.",
            paymentStatusDue: "બાકી",
            paymentStatusDueDescription: "હજુ કોઈ ચુકવણી નોંધાઈ નથી; બાકીની રકમ બાકી છે.",
            completeSale: "વેચાણ પૂર્ણ કરો",
            saleCompleteTitle: "વેચાણ પૂર્ણ થયું",
            saleCompleteMessage: "વેચાણ સફળતાપૂર્વક નોંધાયું છે.",
            saleNumber: "વેચાણ નંબર",
            saleCustomer: "ગ્રાહક",
            saleResultMissing: "પૂર્ણ થયેલું વેચાણ ઉપલબ્ધ નથી. નવું વેચાણ શરૂ કરો.",
            checkoutFailed: "વેચાણ પૂર્ણ થઈ શક્યું નથી. તમારું કાર્ટ ફરી પ્રયાસ માટે તૈયાર છે.",
            showReceipt: "રસીદ જુઓ",
            hideReceipt: "રસીદ છુપાવો",
            shareReceipt: "રસીદ શેર કરો",
            receiptShared: "રસીદ શેર થઈ ગઈ.",
            receiptShareDismissed: "શેરિંગ રદ થયું. વેચાણ પૂર્ણ છે.",
            receiptShareFailed: "રસીદ શેર થઈ શકી નથી. ફરી પ્રયાસ કરો.",
            walkInCustomer: "વૉક-ઇન ગ્રાહક",
            selectCustomer: "ગ્રાહક પસંદ કરો",
            changeCustomer: "ગ્રાહક બદલો",
            clearCustomer: "વૉક-ઇન વાપરો",
            customerPickerTitle: "ગ્રાહક પસંદ કરો",
            customerSearch: "ગ્રાહક શોધો",
            customersDirectorySubtitle: "ગ્રાહકો શોધો અને તેમનો વેચાણ ઇતિહાસ જુઓ.",
            addCustomer: "ગ્રાહક ઉમેરો",
            showCustomerFilters: "ફિલ્ટર બતાવો",
            hideCustomerFilters: "ફિલ્ટર છુપાવો",
            customerStatus: "ગ્રાહક સ્થિતિ",
            customerSort: "ક્રમ",
            customerActive: "સક્રિય",
            customerInactive: "નિષ્ક્રિય",
            customerDue: "બાકી",
            customerAll: "બધા",
            customerSortNameAsc: "નામ A–Z",
            customerSortNameDesc: "નામ Z–A",
            customerSortNewest: "નવા",
            customerSaveFailed: "ગ્રાહક સાચવી શકાયો નથી.",
            customersDirectoryEmpty: "કોઈ ગ્રાહક મળ્યો નથી.",
            customerNoPhone: "ફોન નથી",
            customerBalance: "બેલેન્સ",
            viewCustomer: "જુઓ",
            customersLoadMore: "વધુ ગ્રાહકો લોડ કરો",
            editCustomer: "ગ્રાહક બદલો",
            useCustomerForSale: "હાલના વેચાણમાં વાપરો",
            customerSalesHistory: "વેચાણ ઇતિહાસ",
            salesHistoryLoading: "વેચાણ ઇતિહાસ લોડ થઈ રહ્યો છે...",
            salesHistoryFailed: "વેચાણ ઇતિહાસ લોડ થઈ શક્યો નથી.",
            salesHistoryEmpty: "કોઈ વેચાણ ઇતિહાસ મળ્યો નથી.",
            searchCustomersPlaceholder: "નામ અથવા ફોનથી શોધો",
            customersLoading: "ગ્રાહકો લોડ થઈ રહ્યા છે...",
            customersLoadFailed: "ગ્રાહકો લોડ થઈ શક્યા નથી.",
            noCustomersFound: "કોઈ ગ્રાહક મળ્યો નથી.",
            createCustomer: "ગ્રાહક બનાવો",
            quickCustomer: "ઝડપી ગ્રાહક",
            customerName: "ગ્રાહકનું નામ",
            customerNamePlaceholder: "નામ દાખલ કરો",
            customerPhone: "ગ્રાહકનો ફોન",
            customerPhonePlaceholder: "વૈકલ્પિક ફોન",
            customerNameRequired: "ગ્રાહકનું નામ જરૂરી છે.",
            customerPhoneInvalid: "માન્ય ફોન નંબર દાખલ કરો.",
            customerCreateFailed: "ગ્રાહક બનાવી શકાયો નથી. કૃપા કરીને ફરી પ્રયાસ કરો.",
            cancelCustomerCreation: "રદ કરો",
            saveCustomer: "ગ્રાહક સાચવો",
            orderDiscount: "ઓર્ડર ડિસ્કાઉન્ટ",
            addDiscount: "ડિસ્કાઉન્ટ ઉમેરો",
            editDiscount: "ડિસ્કાઉન્ટ બદલો",
            removeDiscount: "ડિસ્કાઉન્ટ દૂર કરો",
            discountEditorTitle: "ડિસ્કાઉન્ટ",
            discountModeAmount: "રકમ",
            discountModePercent: "ટકા",
            discountValue: "ડિસ્કાઉન્ટ રકમ",
            discountPercentPlaceholder: "ટકા દાખલ કરો",
            discountAmountPlaceholder: "રકમ દાખલ કરો",
            discountInvalid: "વર્તમાન કુલની અંદર માન્ય ડિસ્કાઉન્ટ દાખલ કરો.",
            cancelDiscount: "રદ કરો",
            applyDiscount: "ડિસ્કાઉન્ટ લાગુ કરો",
            saveDraft: "ડ્રાફ્ટ સાચવો",
            updateDraft: "ડ્રાફ્ટ બદલો",
            discardDraft: "ડ્રાફ્ટ કાઢી નાખો",
            draftSaved: "ડ્રાફ્ટ સાચવાયો.",
            draftDiscarded: "ડ્રાફ્ટ કાઢી નાખ્યો.",
            draftActionFailed: "ડ્રાફ્ટ ક્રિયા નિષ્ફળ ગઈ. ફરી પ્રયાસ કરો.",
            reportsSubtitle: "પૂર્ણ થયેલા વેચાણ અને વેચાયેલા પ્રોડક્ટ્સની સમીક્ષા કરો.",
            reportsDate: "તારીખ",
            reportsToday: "આજે",
            reportsAllDates: "બધી તારીખો",
            reportsLoading: "રિપોર્ટ્સ લોડ થઈ રહ્યા છે...",
            reportsLoadFailed: "રિપોર્ટ્સ લોડ થઈ શક્યા નથી.",
            reportsEmpty: "રિપોર્ટનો કોઈ ડેટા મળ્યો નથી.",
            salesSummary: "વેચાણનો સારાંશ",
            salesCount: "વેચાણની સંખ્યા",
            salesValue: "વેચાણની રકમ",
            collectedAmount: "વસૂલ થયેલી રકમ",
            dueAmount: "બાકી રકમ",
            averageSaleValue: "સરેરાશ વેચાણ રકમ",
            productsSold: "વેચાયેલા પ્રોડક્ટ્સ",
            noProductsSold: "કોઈ પ્રોડક્ટ વેચાયો નથી.",
            settingsSubtitle: "ભાષા, દેખાવ, પ્રિન્ટર ઍક્સેસ અને સત્ર સેટિંગ્સ બદલો.",
            settingsTheme: "થીમ",
            themeLight: "લાઇટ",
            themeDark: "ડાર્ક",
            themeSystem: "સિસ્ટમ",
            themeActive: "સક્રિય થીમ: {{theme}}",
            settingsDisplaySize: "ડિસ્પ્લેનું કદ",
            displayStandard: "સ્ટાન્ડર્ડ",
            displayLarge: "મોટું",
            settingsPrinter: "પ્રિન્ટર",
            printerSettings: "પ્રિન્ટર સેટિંગ્સ",
            printerSettingsDeferred: "બ્લૂટૂથ પ્રિન્ટર સેટઅપ પ્રિન્ટિંગ તબક્કામાં ઉપલબ્ધ થશે.",
            storeInformation: "સ્ટોર અને ડિવાઇસની માહિતી",
            organizationName: "સંસ્થા",
            storeName: "સ્ટોર",
            deviceName: "ડિવાઇસ",
            printerSettingsSubtitle: "બ્લૂટૂથ થર્મલ પ્રિન્ટર શોધો અને તેનું પરીક્ષણ કરો.",
            selectedPrinter: "પસંદ કરેલો પ્રિન્ટર",
            discoverPrinters: "પ્રિન્ટર્સ શોધો",
            connectPrinter: "પ્રિન્ટર કનેક્ટ કરો",
            disconnectPrinter: "પ્રિન્ટર ડિસ્કનેક્ટ કરો",
            testPrint: "ટેસ્ટ પ્રિન્ટ",
            retryPrinter: "પ્રિન્ટર ક્રિયા ફરી કરો",
            printerDisconnected: "પ્રિન્ટર ડિસ્કનેક્ટ થયેલ છે",
            printerDiscovering: "પ્રિન્ટર્સ શોધાઈ રહ્યા છે...",
            printerConnecting: "પ્રિન્ટર કનેક્ટ થઈ રહ્યું છે...",
            printerConnected: "પ્રિન્ટર કનેક્ટ થયેલ છે",
            printerTesting: "પ્રિન્ટરનું પરીક્ષણ થઈ રહ્યું છે...",
            printerPrinting: "પ્રિન્ટ થઈ રહ્યું છે...",
            printerFailed: "પ્રિન્ટર ક્રિયા નિષ્ફળ ગઈ",
            printReceipt: "રસીદ પ્રિન્ટ કરો",
            printerPrintFailed: "રસીદ પ્રિન્ટ થઈ શકી નથી. વેચાણ હજુ પૂર્ણ છે.",
        },
    },
    hi: {
        common: {
            appName: "गणत्री POS",
            loading: "लोड हो रहा है",
            retry: "फिर कोशिश करें",
            cancel: "रद्द करें",
            save: "सहेजें",
            logout: "लॉग आउट",
            loggingOut: "लॉग आउट हो रहा है...",
            loggedOutTitle: "लॉग आउट हो गया",
            loggedOutMessage: "आप सफलतापूर्वक लॉग आउट हो गए हैं।",
            logoutFailedTitle: "लॉग आउट विफल",
            genericError: "कृपया फिर कोशिश करें।",
            language: "भाषा",
            english: "English",
            gujarati: "ગુજરાતી",
            hindi: "हिन्दी",
        },
        pos: {
            workspaceTitle: "POS कार्यक्षेत्र",
            foundationMessage:
                "POS की नींव तैयार है। उत्पाद चयन, कार्ट और चेकआउट अपने निर्धारित चरणों में जोड़े जाएंगे।",
            unlockTitle: "POS अनलॉक करें",
            unlockSubtitle: "बिलिंग शुरू करने के लिए अपने स्टोर डिवाइस की जानकारी दें।",
            organizationUsername: "संगठन उपयोगकर्ता नाम",
            deviceUsername: "डिवाइस उपयोगकर्ता नाम",
            deviceSecret: "डिवाइस सीक्रेट",
            unlockPos: "POS अनलॉक करें",
            unlockingPos: "POS अनलॉक हो रहा है...",
            invalidField: "कृपया यह फ़ील्ड जाँचें।",
            invalidCredentials: "डिवाइस की जानकारी मान्य नहीं है।",
            inactiveDevice: "यह डिवाइस निष्क्रिय है। अपने एडमिनिस्ट्रेटर से संपर्क करें।",
            networkFailure: "POS सेवा से संपर्क नहीं हो सका। कनेक्शन जाँचकर फिर कोशिश करें।",
            unlockFailed: "POS अनलॉक नहीं हो सका। कृपया फिर कोशिश करें।",
            storageUnavailable: "सुरक्षित POS स्टोरेज उपलब्ध नहीं है। कृपया फिर कोशिश करें।",
            sessionVerificationFailed: "POS सत्र की जाँच नहीं हो सकी। कृपया फिर अनलॉक करें।",
            newSale: "नई बिक्री",
            bills: "बिल",
            billsSales: "बिक्री",
            billsDrafts: "ड्राफ्ट",
            draft: "ड्राफ्ट",
            saleStatusVoided: "रद्द",
            customers: "ग्राहक",
            reports: "रिपोर्ट",
            settings: "सेटिंग्स",
            tables: "टेबल",
            kitchen: "किचन",
            kitchenSubtitle: "बकाया किचन टिकट पूरे करें।",
            kitchenUnavailable: "इस स्टोर के लिए किचन टिकट चालू नहीं हैं।",
            kitchenLoading: "किचन लोड हो रहा है...",
            kitchenLoadFailed: "किचन टिकट लोड नहीं हो सके।",
            kitchenEmpty: "कोई लंबित किचन टिकट नहीं है।",
            kotNumber: "KOT {{number}}",
            kotTable: "टेबल: {{table}}",
            kotItems: "आइटम",
            completeKot: "KOT पूरा करें",
            kotCompleteFailed: "KOT पूरा नहीं हो सका। फिर कोशिश करें।",
            sendToKitchen: "किचन में भेजें",
            kotSent: "KOT किचन में भेजा गया।",
            kotSendFailed: "KOT भेजा नहीं जा सका। आपका कार्ट फिर कोशिश के लिए तैयार है।",
            tablesSubtitle: "रेस्टोरेंट टेबल ऑर्डर शुरू या फिर से खोलें।",
            tablesUnavailable: "इस स्टोर के लिए टेबल प्रबंधन चालू नहीं है।",
            tablesLoading: "टेबल लोड हो रही हैं...",
            tablesLoadFailed: "टेबल लोड नहीं हो सकीं।",
            tablesEmpty: "कोई टेबल कॉन्फ़िगर नहीं है।",
            tableCapacity: "सीटें: {{count}}",
            tableTotal: "वर्तमान कुल: {{total}}",
            startTableOrder: "ऑर्डर शुरू करें",
            openTableOrder: "ऑर्डर खोलें",
            tableStateFree: "खाली",
            tableStateAllocated: "आवंटित",
            tableStateEngaged: "चल रहा है",
            tableStateReadyToBill: "बिल के लिए तैयार",
            tableStatePaymentDue: "भुगतान बाकी",
            tableStatePaid: "भुगतान किया गया",
            comingSoon: "यह कार्यक्षेत्र अपने निर्धारित चरण में जोड़ा जाएगा।",
            back: "वापस",
            billsSubtitle: "आज की बिक्री खोजें और उनकी भुगतान स्थिति देखें।",
            billsSearch: "बिल खोजें",
            billsSearchPlaceholder: "बिक्री नंबर या ग्राहक से खोजें",
            billsFilter: "फ़िल्टर दिखाएँ",
            billsHideFilters: "फ़िल्टर छिपाएँ",
            billsDate: "तारीख",
            billsToday: "आज",
            billsAllDates: "सभी तारीखें",
            billsPaymentStatus: "भुगतान स्थिति",
            billsPaymentMethod: "भुगतान का तरीका",
            billsAll: "सभी",
            billsClearFilters: "फ़िल्टर साफ़ करें",
            billsLoading: "बिल लोड हो रहे हैं...",
            billsLoadFailed: "बिल लोड नहीं हो सके।",
            billsNoSales: "इस तारीख के लिए कोई बिक्री नहीं मिली।",
            billsNoDrafts: "कोई ड्राफ्ट नहीं मिला।",
            billsNoMatchingSales: "इन फ़िल्टर से कोई बिक्री नहीं मिली।",
            billsSaleNumber: "बिक्री नंबर",
            billsCustomer: "ग्राहक",
            billsLoadMore: "और बिक्री लोड करें",
            saleDetails: "बिक्री का विवरण",
            saleDetailsComingSoon: "बिल के अगले चरण में बिक्री की विस्तृत समीक्षा उपलब्ध होगी।",
            saleDetailsLoading: "बिक्री का विवरण लोड हो रहा है...",
            saleDetailsLoadFailed: "बिक्री का विवरण लोड नहीं हो सका।",
            saleDetailsNoData: "बिक्री का विवरण उपलब्ध नहीं है।",
            saleItems: "वस्तुएँ",
            salePayments: "भुगतान",
            saleSubtotal: "उप-योग",
            saleDiscount: "छूट",
            saleTotal: "कुल",
            resumeDraft: "ड्राफ्ट फिर शुरू करें",
            resumeDraftConfirm: "क्या मौजूदा कार्ट को इस ड्राफ्ट से बदलना है?",
            draftResumeFailed: "यह ड्राफ्ट फिर शुरू नहीं हो सकता क्योंकि इसका कैटलॉग डेटा अब उपलब्ध नहीं है।",
            discardDraftConfirm: "यह ड्राफ्ट हटाएँ? इस क्रिया को वापस नहीं किया जा सकता।",
            restaurantTools: "रेस्टोरेंट टूल्स",
            productSearch: "उत्पाद खोजें",
            searchProductsPlaceholder: "उत्पाद खोजें",
            catalogLoading: "उत्पाद और श्रेणियाँ लोड हो रही हैं...",
            catalogLoadFailed: "उत्पाद और श्रेणियाँ लोड नहीं हो सकीं।",
            catalogAccessDenied: "इस स्टोर को POS कैटलॉग की अनुमति नहीं है।",
            catalogEmpty: "अभी कोई उत्पाद या श्रेणी उपलब्ध नहीं है।",
            catalogReady: "कैटलॉग लोड हो गया। उत्पाद चयन अगली कड़ी में जोड़ा जाएगा।",
            allCategories: "सभी",
            noProductsFound: "इस खोज के लिए कोई उत्पाद नहीं मिला।",
            configurationComingSoon: "कॉन्फ़िगरेशन जल्द उपलब्ध होगा।",
            scanBarcode: "बारकोड स्कैन करें",
            closeScanner: "स्कैनर बंद करें",
            scannerPermissionDenied: "स्कैन करने के लिए कैमरा अनुमति आवश्यक है। आप मैन्युअल रूप से खोज सकते हैं।",
            scannerCameraError: "कैमरा शुरू नहीं हो सका। आप मैन्युअल रूप से खोज सकते हैं।",
            scannerUnknownCode: "इस कोड से कोई उत्पाद नहीं मिला। मैन्युअल रूप से खोजें या दूसरा कोड आज़माएँ।",
            scannerAmbiguousCode: "इस कोड से एक से अधिक उत्पाद मिले। मैन्युअल रूप से खोजें।",
            scannerAdded: "उत्पाद कार्ट में जोड़ा गया।",
            scannerConfigurationComingSoon: "कार्ट में जोड़ने से पहले इस उत्पाद का कॉन्फ़िगरेशन आवश्यक है।",
            allProducts: "सभी उत्पाद",
            recentProducts: "हाल के",
            pinnedProducts: "पिन किए गए",
            pinProduct: "उत्पाद पिन करें",
            unpinProduct: "उत्पाद अनपिन करें",
            configureProduct: "उत्पाद कॉन्फ़िगर करें",
            configurationRequired: "इस उत्पाद को जोड़ने से पहले उपलब्ध विकल्प चुनें।",
            configurationLoading: "उत्पाद के विकल्प लोड हो रहे हैं...",
            configurationLoadFailed: "उत्पाद के विकल्प लोड नहीं हो सके।",
            noConfigurationOptions: "कोई कॉन्फ़िगरेशन विकल्प उपलब्ध नहीं है।",
            cancelConfiguration: "रद्द करें",
            addConfiguredProduct: "कार्ट में जोड़ें",
            cartWithCount: "कार्ट ({{count}})",
            newSaleSubtitle: "कार्ट में जोड़ने के लिए उत्पाद खोजें, स्कैन करें या चुनें।",
            serviceMode: "सेवा मोड",
            serviceModeDineIn: "डाइन-इन",
            serviceModePickUp: "पिक-अप",
            tableOrder: "टेबल ऑर्डर",
            catalogComingSoon: "कैटलॉग चरण में उत्पाद के परिणाम उपलब्ध होंगे।",
            cart: "कार्ट",
            emptyCart: "कार्ट खाली है",
            cartLineUnitPrice: "इकाई कीमत: {{price}}",
            cartLineSellingQuantity: "बिक्री मात्रा: {{quantity}}",
            editSellingQuantity: "मात्रा बदलें",
            sellingQuantity: "बिक्री मात्रा",
            sellingQuantityPlaceholder: "मात्रा दर्ज करें",
            sellingQuantityInvalid: "2 दशमलव तक की सकारात्मक मात्रा दर्ज करें।",
            applySellingQuantity: "मात्रा लागू करें",
            cancelSellingQuantity: "रद्द करें",
            decreaseQuantity: "मात्रा घटाएँ",
            increaseQuantity: "मात्रा बढ़ाएँ",
            removeCartItem: "हटाएँ",
            cartSubtotal: "उप-योग",
            catalogDiscount: "उत्पाद छूट",
            cartDisplayTotal: "दिखाया गया कुल",
            cartDisplayTotalNote: "पूरा करने से पहले अंतिम कुल सर्वर द्वारा तय किया जाएगा।",
            configurationDetails: "कॉन्फ़िगरेशन",
            continueToPayment: "भुगतान पर जाएँ",
            paymentTitle: "भुगतान",
            paymentTotal: "कुल",
            paymentCollected: "प्राप्त राशि",
            paymentRemaining: "बाकी",
            paymentServerNote: "अंतिम भुगतान स्थिति और कुल सर्वर द्वारा तय किए जाते हैं।",
            paymentRow: "भुगतान {{count}}",
            paymentMethod: "भुगतान का तरीका",
            paymentCash: "नकद",
            paymentUpi: "UPI",
            paymentCard: "कार्ड",
            paymentAmount: "राशि",
            paymentAmountPlaceholder: "राशि दर्ज करें",
            paymentInvalidAmount: "मान्य गैर-ऋणात्मक राशि दर्ज करें।",
            paymentOverTotal: "प्राप्त राशि कुल से अधिक नहीं हो सकती।",
            addPayment: "भुगतान जोड़ें",
            removePayment: "हटाएँ",
            continueToCompleteSale: "बिक्री पूरी करने के लिए आगे बढ़ें",
            paymentCheckoutComingSoon: "बिक्री पूरी करना अगले चरण में उपलब्ध होगा।",
            backToCart: "कार्ट पर वापस जाएँ",
            paymentStatusPaid: "भुगतान किया गया",
            paymentStatusPaidDescription: "बिक्री की पूरी राशि का भुगतान हो गया है।",
            paymentStatusPartial: "आंशिक",
            paymentStatusPartialDescription: "कुछ भुगतान प्राप्त हुआ है; बाकी राशि देय है।",
            paymentStatusDue: "बाकी",
            paymentStatusDueDescription: "अभी कोई भुगतान दर्ज नहीं है; बाकी राशि देय है।",
            completeSale: "बिक्री पूरी करें",
            saleCompleteTitle: "बिक्री पूरी हुई",
            saleCompleteMessage: "बिक्री सफलतापूर्वक दर्ज हो गई है।",
            saleNumber: "बिक्री नंबर",
            saleCustomer: "ग्राहक",
            saleResultMissing: "पूरी हुई बिक्री उपलब्ध नहीं है। नई बिक्री शुरू करें।",
            checkoutFailed: "बिक्री पूरी नहीं हो सकी। आपका कार्ट फिर से प्रयास के लिए तैयार है।",
            showReceipt: "रसीद देखें",
            hideReceipt: "रसीद छिपाएँ",
            shareReceipt: "रसीद साझा करें",
            receiptShared: "रसीद साझा हो गई।",
            receiptShareDismissed: "साझा करना रद्द हुआ। बिक्री अभी भी पूरी है।",
            receiptShareFailed: "रसीद साझा नहीं हो सकी। फिर से प्रयास करें।",
            walkInCustomer: "वॉक-इन ग्राहक",
            selectCustomer: "ग्राहक चुनें",
            changeCustomer: "ग्राहक बदलें",
            clearCustomer: "वॉक-इन इस्तेमाल करें",
            customerPickerTitle: "ग्राहक चुनें",
            customerSearch: "ग्राहक खोजें",
            customersDirectorySubtitle: "ग्राहक खोजें और उनकी बिक्री का इतिहास देखें।",
            addCustomer: "ग्राहक जोड़ें",
            showCustomerFilters: "फ़िल्टर दिखाएँ",
            hideCustomerFilters: "फ़िल्टर छिपाएँ",
            customerStatus: "ग्राहक स्थिति",
            customerSort: "क्रम",
            customerActive: "सक्रिय",
            customerInactive: "निष्क्रिय",
            customerDue: "बाकी",
            customerAll: "सभी",
            customerSortNameAsc: "नाम A–Z",
            customerSortNameDesc: "नाम Z–A",
            customerSortNewest: "नवीनतम",
            customerSaveFailed: "ग्राहक सहेजा नहीं जा सका।",
            customersDirectoryEmpty: "कोई ग्राहक नहीं मिला।",
            customerNoPhone: "फोन नहीं है",
            customerBalance: "बैलेंस",
            viewCustomer: "देखें",
            customersLoadMore: "और ग्राहक लोड करें",
            editCustomer: "ग्राहक बदलें",
            useCustomerForSale: "वर्तमान बिक्री में उपयोग करें",
            customerSalesHistory: "बिक्री इतिहास",
            salesHistoryLoading: "बिक्री इतिहास लोड हो रहा है...",
            salesHistoryFailed: "बिक्री इतिहास लोड नहीं हो सका।",
            salesHistoryEmpty: "बिक्री इतिहास नहीं मिला।",
            searchCustomersPlaceholder: "नाम या फोन से खोजें",
            customersLoading: "ग्राहक लोड हो रहे हैं...",
            customersLoadFailed: "ग्राहक लोड नहीं हो सके।",
            noCustomersFound: "कोई ग्राहक नहीं मिला।",
            createCustomer: "ग्राहक बनाएँ",
            quickCustomer: "त्वरित ग्राहक",
            customerName: "ग्राहक का नाम",
            customerNamePlaceholder: "नाम दर्ज करें",
            customerPhone: "ग्राहक का फोन",
            customerPhonePlaceholder: "वैकल्पिक फोन",
            customerNameRequired: "ग्राहक का नाम आवश्यक है।",
            customerPhoneInvalid: "मान्य फोन नंबर दर्ज करें।",
            customerCreateFailed: "ग्राहक नहीं बनाया जा सका। कृपया फिर कोशिश करें।",
            cancelCustomerCreation: "रद्द करें",
            saveCustomer: "ग्राहक सहेजें",
            orderDiscount: "ऑर्डर छूट",
            addDiscount: "छूट जोड़ें",
            editDiscount: "छूट बदलें",
            removeDiscount: "छूट हटाएँ",
            discountEditorTitle: "छूट",
            discountModeAmount: "राशि",
            discountModePercent: "प्रतिशत",
            discountValue: "छूट राशि",
            discountPercentPlaceholder: "प्रतिशत दर्ज करें",
            discountAmountPlaceholder: "राशि दर्ज करें",
            discountInvalid: "वर्तमान कुल के भीतर मान्य छूट दर्ज करें।",
            cancelDiscount: "रद्द करें",
            applyDiscount: "छूट लागू करें",
            saveDraft: "ड्राफ्ट सहेजें",
            updateDraft: "ड्राफ्ट बदलें",
            discardDraft: "ड्राफ्ट हटाएँ",
            draftSaved: "ड्राफ्ट सहेजा गया।",
            draftDiscarded: "ड्राफ्ट हटाया गया।",
            draftActionFailed: "ड्राफ्ट क्रिया विफल हुई। फिर कोशिश करें।",
            reportsSubtitle: "पूरी हुई बिक्री और बिके हुए उत्पादों की समीक्षा करें।",
            reportsDate: "तारीख",
            reportsToday: "आज",
            reportsAllDates: "सभी तारीखें",
            reportsLoading: "रिपोर्ट लोड हो रही हैं...",
            reportsLoadFailed: "रिपोर्ट लोड नहीं हो सकीं।",
            reportsEmpty: "रिपोर्ट का कोई डेटा नहीं मिला।",
            salesSummary: "बिक्री सारांश",
            salesCount: "बिक्री की संख्या",
            salesValue: "बिक्री का मूल्य",
            collectedAmount: "वसूल की गई राशि",
            dueAmount: "बकाया राशि",
            averageSaleValue: "औसत बिक्री मूल्य",
            productsSold: "बिके हुए उत्पाद",
            noProductsSold: "कोई उत्पाद नहीं बिका।",
            settingsSubtitle: "भाषा, रूप, प्रिंटर एक्सेस और सत्र सेटिंग बदलें।",
            settingsTheme: "थीम",
            themeLight: "लाइट",
            themeDark: "डार्क",
            themeSystem: "सिस्टम",
            themeActive: "सक्रिय थीम: {{theme}}",
            settingsDisplaySize: "डिस्प्ले आकार",
            displayStandard: "मानक",
            displayLarge: "बड़ा",
            settingsPrinter: "प्रिंटर",
            printerSettings: "प्रिंटर सेटिंग",
            printerSettingsDeferred: "ब्लूटूथ प्रिंटर सेटअप प्रिंटिंग चरण में उपलब्ध होगा।",
            storeInformation: "स्टोर और डिवाइस की जानकारी",
            organizationName: "संगठन",
            storeName: "स्टोर",
            deviceName: "डिवाइस",
            printerSettingsSubtitle: "ब्लूटूथ थर्मल प्रिंटर खोजें और उसका परीक्षण करें।",
            selectedPrinter: "चुना हुआ प्रिंटर",
            discoverPrinters: "प्रिंटर खोजें",
            connectPrinter: "प्रिंटर कनेक्ट करें",
            disconnectPrinter: "प्रिंटर डिस्कनेक्ट करें",
            testPrint: "टेस्ट प्रिंट",
            retryPrinter: "प्रिंटर क्रिया फिर करें",
            printerDisconnected: "प्रिंटर डिस्कनेक्ट है",
            printerDiscovering: "प्रिंटर खोजे जा रहे हैं...",
            printerConnecting: "प्रिंटर कनेक्ट हो रहा है...",
            printerConnected: "प्रिंटर कनेक्ट है",
            printerTesting: "प्रिंटर का परीक्षण हो रहा है...",
            printerPrinting: "प्रिंट हो रहा है...",
            printerFailed: "प्रिंटर क्रिया विफल हुई",
            printReceipt: "रसीद प्रिंट करें",
            printerPrintFailed: "रसीद प्रिंट नहीं हो सकी। बिक्री अभी भी पूरी है।",
        },
    },
} as const;

export type PosTranslationKey = keyof typeof appResources.en.pos;

export const isAppLanguage = (value: string | null | undefined): value is AppLanguage =>
    Boolean(value && APP_LANGUAGES.includes(value as AppLanguage));

export const resolveAppLanguage = (value: string | null | undefined): AppLanguage =>
    isAppLanguage(value) ? value : DEFAULT_APP_LANGUAGE;
