export const APP_LANGUAGES = ["en", "gu", "hi"] as const;

export type AppLanguage = (typeof APP_LANGUAGES)[number];

export const DEFAULT_APP_LANGUAGE: AppLanguage = "en";

export const appResources = {
    en: {
        common: {
            appName: "Ganatri POS",
            loading: "Loading",
            retry: "Retry",
            cancel: "Cancel",
            save: "Save",
            logout: "Logout",
            loggingOut: "Logging out...",
            loggedOutTitle: "Logged out",
            loggedOutMessage: "You have been logged out successfully.",
            logoutFailedTitle: "Logout failed",
            genericError: "Please try again.",
            language: "Language",
            english: "English",
            gujarati: "ગુજરાતી",
            hindi: "हिन्दी",
        },
        pos: {
            workspaceTitle: "POS workspace",
            foundationMessage:
                "The POS foundation is ready. Product selection, Cart, and checkout will be added in their planned phases.",
            unlockTitle: "Unlock POS",
            unlockSubtitle: "Use your Store Device credentials to start billing.",
            organizationUsername: "Organization username",
            deviceUsername: "Device username",
            deviceSecret: "Device secret",
            unlockPos: "Unlock POS",
            unlockingPos: "Unlocking POS...",
            invalidField: "Please check this field.",
            invalidCredentials: "The Device credentials are not valid.",
            inactiveDevice: "This Device is inactive. Contact your administrator.",
            networkFailure: "Could not reach the POS service. Check the connection and try again.",
            unlockFailed: "POS could not be unlocked. Please try again.",
            storageUnavailable: "Secure POS storage is unavailable. Please try again.",
            sessionVerificationFailed: "The POS session could not be verified. Please unlock again.",
            newSale: "New Sale",
            bills: "Bills",
            customers: "Customers",
            reports: "Reports",
            settings: "Settings",
            tables: "Tables",
            comingSoon: "This workspace will be added in its planned phase.",
            back: "Back",
            restaurantTools: "Restaurant tools",
            productSearch: "Product search",
            searchProductsPlaceholder: "Search products",
            catalogLoading: "Loading Products and Categories...",
            catalogLoadFailed: "Products and Categories could not be loaded.",
            catalogEmpty: "No Products or Categories are available yet.",
            catalogReady: "Catalog loaded. Product selection will be added next.",
            allCategories: "All",
            noProductsFound: "No Products found for this search.",
            configurationComingSoon: "Configuration will be available soon.",
            scanBarcode: "Scan barcode",
            closeScanner: "Close scanner",
            scannerPermissionDenied: "Camera permission is needed to scan. You can still search manually.",
            scannerCameraError: "The camera could not start. You can still search manually.",
            scannerUnknownCode: "No Product matches this code. Search manually or try another code.",
            scannerAmbiguousCode: "More than one Product matches this code. Search manually.",
            scannerAdded: "Product added to Cart.",
            scannerConfigurationComingSoon: "This Product needs configuration before it can be added.",
            cartWithCount: "Cart ({{count}})",
            newSaleSubtitle: "Search, scan, or choose a Product to add it to Cart.",
            catalogComingSoon: "Product results will be available in the Catalog phase.",
            cart: "Cart",
            emptyCart: "Cart is empty",
            cartComingSoon: "Products added from New Sale will appear here in the Cart phase.",
        },
    },
    gu: {
        common: {
            appName: "ગણત્રી POS",
            loading: "લોડ થઈ રહ્યું છે",
            retry: "ફરી પ્રયાસ કરો",
            cancel: "રદ કરો",
            save: "સાચવો",
            logout: "લૉગઆઉટ",
            loggingOut: "લૉગઆઉટ થઈ રહ્યું છે...",
            loggedOutTitle: "લૉગઆઉટ થયું",
            loggedOutMessage: "તમે સફળતાપૂર્વક લૉગઆઉટ થયા છો.",
            logoutFailedTitle: "લૉગઆઉટ નિષ્ફળ",
            genericError: "કૃપા કરીને ફરી પ્રયાસ કરો.",
            language: "ભાષા",
            english: "English",
            gujarati: "ગુજરાતી",
            hindi: "हिन्दी",
        },
        pos: {
            workspaceTitle: "POS કાર્યસ્થળ",
            foundationMessage:
                "POS પાયો તૈયાર છે. પ્રોડક્ટ પસંદગી, કાર્ટ અને ચેકઆઉટ તેમના નિર્ધારિત તબક્કામાં ઉમેરવામાં આવશે.",
            unlockTitle: "POS અનલૉક કરો",
            unlockSubtitle: "બિલિંગ શરૂ કરવા માટે તમારા સ્ટોર ડિવાઇસની વિગતોનો ઉપયોગ કરો.",
            organizationUsername: "સંસ્થાનું યુઝરનેમ",
            deviceUsername: "ડિવાઇસ યુઝરનેમ",
            deviceSecret: "ડિવાઇસ સિક્રેટ",
            unlockPos: "POS અનલૉક કરો",
            unlockingPos: "POS અનલૉક થઈ રહ્યું છે...",
            invalidField: "કૃપા કરીને આ ફીલ્ડ તપાસો.",
            invalidCredentials: "ડિવાઇસની વિગતો માન્ય નથી.",
            inactiveDevice: "આ ડિવાઇસ નિષ્ક્રિય છે. તમારા એડમિનિસ્ટ્રેટરનો સંપર્ક કરો.",
            networkFailure: "POS સેવા સુધી પહોંચી શકાયું નથી. કનેક્શન તપાસી ફરી પ્રયાસ કરો.",
            unlockFailed: "POS અનલૉક થઈ શક્યું નથી. કૃપા કરીને ફરી પ્રયાસ કરો.",
            storageUnavailable: "સુરક્ષિત POS સ્ટોરેજ ઉપલબ્ધ નથી. કૃપા કરીને ફરી પ્રયાસ કરો.",
            sessionVerificationFailed: "POS સત્રની ચકાસણી થઈ શકી નથી. કૃપા કરીને ફરી અનલૉક કરો.",
            newSale: "નવું વેચાણ",
            bills: "બિલ્સ",
            customers: "ગ્રાહકો",
            reports: "રિપોર્ટ્સ",
            settings: "સેટિંગ્સ",
            tables: "ટેબલ્સ",
            comingSoon: "આ કાર્યસ્થળ તેના નિર્ધારિત તબક્કામાં ઉમેરવામાં આવશે.",
            back: "પાછા",
            restaurantTools: "રેસ્ટોરન્ટ સાધનો",
            productSearch: "પ્રોડક્ટ શોધો",
            searchProductsPlaceholder: "પ્રોડક્ટ શોધો",
            catalogLoading: "પ્રોડક્ટ્સ અને કેટેગરીઝ લોડ થઈ રહ્યાં છે...",
            catalogLoadFailed: "પ્રોડક્ટ્સ અને કેટેગરીઝ લોડ થઈ શક્યાં નથી.",
            catalogEmpty: "હજુ સુધી કોઈ પ્રોડક્ટ અથવા કેટેગરી ઉપલબ્ધ નથી.",
            catalogReady: "કેટલોગ લોડ થયો. પ્રોડક્ટ પસંદગી હવે પછી ઉમેરાશે.",
            allCategories: "બધા",
            noProductsFound: "આ શોધ માટે કોઈ પ્રોડક્ટ મળી નથી.",
            configurationComingSoon: "કન્ફિગરેશન ટૂંક સમયમાં ઉપલબ્ધ થશે.",
            scanBarcode: "બારકોડ સ્કેન કરો",
            closeScanner: "સ્કેનર બંધ કરો",
            scannerPermissionDenied: "સ્કેન કરવા માટે કેમેરાની પરવાનગી જરૂરી છે. તમે હજી પણ જાતે શોધી શકો છો.",
            scannerCameraError: "કેમેરા શરૂ થઈ શક્યો નથી. તમે હજી પણ જાતે શોધી શકો છો.",
            scannerUnknownCode: "આ કોડ સાથે કોઈ પ્રોડક્ટ મળ્યું નથી. જાતે શોધો અથવા બીજો કોડ અજમાવો.",
            scannerAmbiguousCode: "આ કોડ સાથે એકથી વધુ પ્રોડક્ટ મળ્યાં છે. જાતે શોધો.",
            scannerAdded: "પ્રોડક્ટ કાર્ટમાં ઉમેરાયું.",
            scannerConfigurationComingSoon: "કાર્ટમાં ઉમેરતા પહેલાં આ પ્રોડક્ટનું કન્ફિગરેશન જરૂરી છે.",
            cartWithCount: "કાર્ટ ({{count}})",
            newSaleSubtitle: "કાર્ટમાં ઉમેરવા માટે પ્રોડક્ટ શોધો, સ્કેન કરો અથવા પસંદ કરો.",
            catalogComingSoon: "કેટલોગ તબક્કામાં પ્રોડક્ટના પરિણામો ઉપલબ્ધ થશે.",
            cart: "કાર્ટ",
            emptyCart: "કાર્ટ ખાલી છે",
            cartComingSoon: "નવા વેચાણમાંથી ઉમેરેલા પ્રોડક્ટ્સ કાર્ટ તબક્કામાં અહીં દેખાશે.",
        },
    },
    hi: {
        common: {
            appName: "गणत्री POS",
            loading: "लोड हो रहा है",
            retry: "फिर कोशिश करें",
            cancel: "रद्द करें",
            save: "सहेजें",
            logout: "लॉग आउट",
            loggingOut: "लॉग आउट हो रहा है...",
            loggedOutTitle: "लॉग आउट हो गया",
            loggedOutMessage: "आप सफलतापूर्वक लॉग आउट हो गए हैं।",
            logoutFailedTitle: "लॉग आउट विफल",
            genericError: "कृपया फिर कोशिश करें।",
            language: "भाषा",
            english: "English",
            gujarati: "ગુજરાતી",
            hindi: "हिन्दी",
        },
        pos: {
            workspaceTitle: "POS कार्यक्षेत्र",
            foundationMessage:
                "POS की नींव तैयार है। उत्पाद चयन, कार्ट और चेकआउट अपने निर्धारित चरणों में जोड़े जाएंगे।",
            unlockTitle: "POS अनलॉक करें",
            unlockSubtitle: "बिलिंग शुरू करने के लिए अपने स्टोर डिवाइस की जानकारी दें।",
            organizationUsername: "संगठन उपयोगकर्ता नाम",
            deviceUsername: "डिवाइस उपयोगकर्ता नाम",
            deviceSecret: "डिवाइस सीक्रेट",
            unlockPos: "POS अनलॉक करें",
            unlockingPos: "POS अनलॉक हो रहा है...",
            invalidField: "कृपया यह फ़ील्ड जाँचें।",
            invalidCredentials: "डिवाइस की जानकारी मान्य नहीं है।",
            inactiveDevice: "यह डिवाइस निष्क्रिय है। अपने एडमिनिस्ट्रेटर से संपर्क करें।",
            networkFailure: "POS सेवा से संपर्क नहीं हो सका। कनेक्शन जाँचकर फिर कोशिश करें।",
            unlockFailed: "POS अनलॉक नहीं हो सका। कृपया फिर कोशिश करें।",
            storageUnavailable: "सुरक्षित POS स्टोरेज उपलब्ध नहीं है। कृपया फिर कोशिश करें।",
            sessionVerificationFailed: "POS सत्र की जाँच नहीं हो सकी। कृपया फिर अनलॉक करें।",
            newSale: "नई बिक्री",
            bills: "बिल",
            customers: "ग्राहक",
            reports: "रिपोर्ट",
            settings: "सेटिंग्स",
            tables: "टेबल",
            comingSoon: "यह कार्यक्षेत्र अपने निर्धारित चरण में जोड़ा जाएगा।",
            back: "वापस",
            restaurantTools: "रेस्टोरेंट टूल्स",
            productSearch: "उत्पाद खोजें",
            searchProductsPlaceholder: "उत्पाद खोजें",
            catalogLoading: "उत्पाद और श्रेणियाँ लोड हो रही हैं...",
            catalogLoadFailed: "उत्पाद और श्रेणियाँ लोड नहीं हो सकीं।",
            catalogEmpty: "अभी कोई उत्पाद या श्रेणी उपलब्ध नहीं है।",
            catalogReady: "कैटलॉग लोड हो गया। उत्पाद चयन अगली कड़ी में जोड़ा जाएगा।",
            allCategories: "सभी",
            noProductsFound: "इस खोज के लिए कोई उत्पाद नहीं मिला।",
            configurationComingSoon: "कॉन्फ़िगरेशन जल्द उपलब्ध होगा।",
            scanBarcode: "बारकोड स्कैन करें",
            closeScanner: "स्कैनर बंद करें",
            scannerPermissionDenied: "स्कैन करने के लिए कैमरा अनुमति आवश्यक है। आप मैन्युअल रूप से खोज सकते हैं।",
            scannerCameraError: "कैमरा शुरू नहीं हो सका। आप मैन्युअल रूप से खोज सकते हैं।",
            scannerUnknownCode: "इस कोड से कोई उत्पाद नहीं मिला। मैन्युअल रूप से खोजें या दूसरा कोड आज़माएँ।",
            scannerAmbiguousCode: "इस कोड से एक से अधिक उत्पाद मिले। मैन्युअल रूप से खोजें।",
            scannerAdded: "उत्पाद कार्ट में जोड़ा गया।",
            scannerConfigurationComingSoon: "कार्ट में जोड़ने से पहले इस उत्पाद का कॉन्फ़िगरेशन आवश्यक है।",
            cartWithCount: "कार्ट ({{count}})",
            newSaleSubtitle: "कार्ट में जोड़ने के लिए उत्पाद खोजें, स्कैन करें या चुनें।",
            catalogComingSoon: "कैटलॉग चरण में उत्पाद के परिणाम उपलब्ध होंगे।",
            cart: "कार्ट",
            emptyCart: "कार्ट खाली है",
            cartComingSoon: "नई बिक्री से जोड़े गए उत्पाद कार्ट चरण में यहाँ दिखेंगे।",
        },
    },
} as const;

export type PosTranslationKey = keyof typeof appResources.en.pos;

export const isAppLanguage = (value: string | null | undefined): value is AppLanguage =>
    Boolean(value && APP_LANGUAGES.includes(value as AppLanguage));

export const resolveAppLanguage = (value: string | null | undefined): AppLanguage =>
    isAppLanguage(value) ? value : DEFAULT_APP_LANGUAGE;
